### ISSUE TITLE
Tag/version mismatch

### ISSUE THREAD

**Issue by liamdawson** [envato/ejson_wrapper#8]
According to the commit message and latest tag, the gem version is `4.0.0`.

According to https://rubygems.org/gems/ejson_wrapper, the latest version is `0.4.0`.

I'm assuming `0.4.0` [is correct](https://github.com/envato/ejson_wrapper/blob/master/lib/ejson_wrapper/version.rb#L2)?

**Comment by runlevel5** [comment]
It should be `0.4.0` cc @viraptor

**Comment by viraptor** [comment]
Yeah, 0.4.0 is correct. I'll fix up the tag, but the commits will stay the same.

**Comment by viraptor** [comment]
Tag's fixed. I don't expect the commit message will impact anything, but let me know if it does.
